import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";
import { Navbar } from "./Components/Navbar";
import NextTopLoader from 'nextjs-toploader';

const inter = Karla({weight:"400",subsets:["latin"]})

export const metadata: Metadata = {
  title: "W-airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-base`}>

      <NextTopLoader  color="#F32C49"/>
        <Navbar />
        {children}
        </body>
    </html>
  );
}
